site_name: (Software) User Documentation

theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - palette: 
      primary: Light green
      accent: deep blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
