site_name: Discord User Documentation

theme:
  name: material
  icon:
    admonition:
      note: octicons/question-16
  palette:
    # Palette toggle for light mode
    - palette:
      primary: Light green
      accent: deep blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      
  features:
    - toc.integrate

  markdown_extensions:
    - attr_list
    - md_in_html
    - def_list
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - codehilite
