site_name: Discord User Documentation

nav:
  - Home: index.md
  - task1.md
  - task2.md
  - task3.md
  - troubleshooting.md
  - glossary.md

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite

theme:
  name: material
  icon:
    admonition:
      info: fontawesome/solid/circle-info
      warning: fontawesome/solid/triangle-exclamation
      success: fontawesome/solid/check

  palette:
    # Palette toggle for light mode
    - palette:
      primary: Light green
      accent: deep blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - toc.integrate
